project_name: luminox-cli

# Build configuration
builds:
  - id: luminox-cli
    main: main.go
    binary: luminox-cli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

# Archive configuration
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - templates/**/*

# Checksums
checksum:
  name_template: 'checksums.txt'

# Snapshots (for testing)
snapshot:
  name_template: "{{ .Tag }}-next"

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Release
release:
  github:
    owner: memodb-io
    name: Luminox
  mode: replace
  draft: false
  prerelease: auto

# Homebrew (macOS)
brews:
  - name: luminox-cli
    tap:
      owner: memodb-io
      name: homebrew-tap
    homepage: https://luminox.io
    description: Luminox CLI - Build context-aware AI applications
    license: MIT
    test: |
      system "#{bin}/luminox-cli version"
    install: |
      bin.install "luminox-cli" => "luminox"
    commit_author:
      name: Luminox Bot
      email: bot@luminox.io

# Build hooks
before:
  hooks:
    - go mod download
    - go mod tidy

